# -*- coding: utf-8 -*-
"""data1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hFWt5zecfgqQM9voAwSQFZfpauQ8nYoF
"""

from google.colab import drive
drive.mount('/content/drive')
import matplotlib.pyplot as plt
import pandas as pd
plt.style.use("classic")
data=pd.read_csv('/Housing.csv')
data.head()
data.set_index('bedrooms').plot(kind='bar')
plt.figure(figsize=(17,0))
plt.title("price Distribution")
plt.xlabel("price")
plt.ylabel("price count")
plt.show()

"""# New Section"""